gabrielcol_sylius_rec_ai_admin_property:
    resource: |
        section: admin
        alias: gabrielcol_sylius_rec_ai.property
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: gabrielcol_sylius_rec_ai_admin_property
        vars:
            all:
                subheader: gabrielcol_sylius_rec_ai.ui.property
            index:
                icon: 'bullhorn'
    type: sylius.resource
