sylius_grid:
    grids:
        gabrielcol_sylius_rec_ai_admin_property:
            driver:
                name: doctrine/orm
                options:
                    class: "%gabrielcol_sylius_rec_ai.model.property.class%"
            fields:
                projectName:
                    type: string
                    label: gabrielcol_sylius_rec_ai.ui.projectName
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
                channels:
                    type: twig
                    label: sylius.ui.channels
                    options:
                        template: "@GabrielcolSyliusRecommendationAIPlugin/Admin/Grid/Field/channels.html.twig"
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
